### ISSUE TITLE
Horário de reunião

### ISSUE THREAD

**Issue by alissonfpmorais** [training-center/kotlin-study-group#1]
Pessoal, por favor respondam esse [formulário](https://goo.gl/forms/we4c1yPodtz9MPC02) pra gente ver qual o melhor horário pra reunião.

Assim que todos responderem, eu publico o resultado aqui pra marcarmos a primeira.

Quaisquer sugestões ou feedback, por favor fiquem à vontade 👍 

Obrigado!!

**Comment by guilhermeoa07** [comment]
Pra mim, durante a semana a partir das 19 e fim de semana durante o dia é tranquilo.

**Comment by bloderxd** [comment]
A partir das 20h durante semana e fim de semana apartir das 14h.

**Comment by amadeu01** [comment]
Em `horário` no formulário tá aparecendo assim

![image](https://user-images.githubusercontent.com/11631092/45049925-656b3180-b056-11e8-94b3-0603aa5fe747.png)

Para colocar uma data.

Melhor horário apra mim é depois das 22:00 dia de semana e no final de semana qualquer horário, mas preciso saber disso bem antes ahhaha

**Comment by alissonfpmorais** [comment]
Nossa @amadeu01, dei bobeira e selecionei o tipo errado.
Tá corrigido já, se puder responder novamente.

Valeu pelo toque o/

**Comment by amadeu01** [comment]
@alissonfpmorais ficou definido algum horário?

**Comment by alissonfpmorais** [comment]
@amadeu01 não ficou. Nem 1/3 respondeu o questionário ou comentou qualquer coisa nessa issue ou no slack.

Acho que teremos que começar com a galera que apareceu e o restante vem aparecendo (ou comentando outros horários) depois, se não esse grupo não inicia os estudos.

**Comment by Diego-Brocanelli** [comment]
Olá, pessoal.

Para tentar auxiliar nesse impasse, façam a reunião com os membros que se interessaram, não percam essa oportunidade, mesmo que seja 2 ou 3 pessoas, porém vocês podem tocar o barco fazer reuniões e conforme for passando os interessados vão aderindo ao processo.

**Comment by Diego-Brocanelli** [comment]
Olá, pessoal.

Podemos encerrar essa issue, ou ainda se mantém relevante para permanecer aberta?

**Comment by amadeu01** [comment]
Estamos indo bem, mas agora. Acabou que o grupo inteiro meio que parou de se comunicar.
Acho que pode fechar essa issue e vamos tentar reativar o pessoal pelo slack
