### ISSUE TITLE
Roadmap de estudos

### ISSUE THREAD

**Issue by alissonfpmorais** [training-center/kotlin-study-group#2]
Galera, temos que definir quais assuntos e ordem que vamos abordar.

Minha sugestão é a seguinte: cada um de nós trazer um (ou mais) conteúdos que ache relevante para os estudos e de acordo com a complexidade estruturamos um roadmap pra seguirmos. O que acham?
Vou fazer um compilado do que já tenho e publico aqui em breve.

Espaço aqui tá livre para sugestões, lembrando que quanto mais sugestões melhor será nosso roadmap/estudo 👍 

Valeu gente!

**Comment by gustavobite** [comment]
Podíamos separar em 3 níveis.. 
1) Básico
- Kotlin
- Functional Programming
2) Intermediário
- tips and tricks
- best practices
3) Avançado
- criamos um projeto open-source pra praticar (full kotlin - backend e android, por exemplo)
- geramos conteúdo.. posts.. e etc.. (compartilhar conhecimento)

**Comment by matheusbristot** [comment]
vai ser kotlin puro ou kotlin-android?

**Comment by amadeu01** [comment]
Pessoal, eu criei um trello com o Roadmap que eu fiz, daí, se vocês quiserem contribuir, posso ir adicionando vocês 😄

**Comment by alissonfpmorais** [comment]
Muito bom galera, vamos contribuindo mesmo!

@gustavobite acho que a ideia de dividir por níveis é mais ou menos isso mesmo. Eu acho que puxaria só programação funcional mais pra frente um pouco, pra galera pegar bem as features da linguagem antes. Eu particularmente virei adepto de programação funcional (uso sempre que possível), mas como é um grupo de uma linguagem e não do paradigma, podemos acabar excluindo quem tá a fim de aprender voltado pra OO, por exemplo. O que acha?
Quanto a criar projetos open-source e gerar conteúdo, não tenho nem o que dizer, topo demais!! 🎉 
Criei uma [issue](https://github.com/training-center/kotlin-study-group/issues/3) pra compartilhar ideias de projeto, então se já tiver alguma coisa na cabeça, manda lá 👍 

@matheusbristot a princípio não será voltado pra nenhuma plataforma, mas nada nos impede de colocarmos no roadmap estudos relacionados a Android (assim como Desktop, Web, iOS, etc), inclusive os projetos que formos fazendo durantes os estudos podem envolver essas plataformas. Acho que ficaria bem legal aprender a linguagem e colocando a mão na massa em situações reais. No momento seu foco maior é Android?

Apenas pra complementar o comentário do @amadeu01, segue aí o [roadmap](https://trello.com/invite/b/tyvlJzIK/a5bd2cb7f505ef1a64de495151f3cee6/kotlin-roadmap) que ele criou. Ficou show! Tem bastante coisa já pra estudar e vou adicionar mais algumas que podem interessar a galera também. 

Quanto ao roadmap to pesquisando alguns livros, cursos e artigos pra ver qual o conteúdo e ordem de estudo, talvez dê pra gente usar como base também.

**Comment by alissonfpmorais** [comment]
Galera, transformei o trello que o @amadeu01 fez em um mindmap. Acho que fica bem visual e da um boa ideia do fluxo a seguir. O que acham? Da pra seguir essa trilha?

![mindmap](https://user-images.githubusercontent.com/26880912/45566666-c56b9000-b82d-11e8-99f2-ab43a489d55d.png)

**Comment by amadeu01** [comment]
@alissonfpmorais achei massa! Acho que poderia ter um BDD no intermediário. Acho que já podemos seguir nesse fluxo aí 😄

**Comment by alissonfpmorais** [comment]
@amadeu01 fiz a alteração que sugeriu, da uma olhada

**Comment by Diego-Brocanelli** [comment]
Olá, pessoal.

Podemos encerrar essa issue, ou ainda se mantém relevante para permanecer aberta?

**Comment by amadeu01** [comment]
Acho que pode fechar a issue
