### ISSUE TITLE
Projetos para estudos

### ISSUE THREAD

**Issue by alissonfpmorais** [training-center/kotlin-study-group#3]
Galera o/

Abri essa issue aqui para postarmos ideias bacanas de projetos para desenvolvermos ao longo dos estudos, vai ser nosso pequeno banco de ideias. Então se tiver algum problema durante seu desenvolvimento, não encontrou alguma lib pra aquele trecho de código ou tem alguma ideia muito mirabolante e super divertida de implementar, compartilhar aqui.

**Comment by alissonfpmorais** [comment]
Pra dar a largada, vou sugerir uma lib open-source pra web scrapping.
Conheço bibliotecas legais de usar para outras linguagens, mas pra Java/Kotlin só conheço Selenium. Dá pra usar, mas não vejo nada de user-friendly na forma de programar.
Uma lib que fornece uma DSL (incluindo a possibilidade de realizar ações) seria, não apenas muito legal, mas também contribuiria bastante na área de data science.

**Comment by amadeu01** [comment]
Acho massa fazer web scrapping.
Tem essa lib em python [Scrapy](https://scrapy.org/) que tem como usar ela de exemplo para fazer coisas em kotlin hehe

**Comment by Diego-Brocanelli** [comment]
Olá, pessoal.

Podemos encerrar essa issue, ou ainda se mantém relevante para permanecer aberta?

**Comment by amadeu01** [comment]
Acho que pode fechar a issue.
